### ISSUE TITLE
Remove .DS_Store

### ISSUE THREAD

**Issue by geniuskouta** [kenthiroi/AA_Classwork#1]
# Remove .DS_Store

.DS_Store file is created in each directory on Mac file system but it's not a development related file. You should not track them on git!

1. remove .DS_Store in each directory
```
find . -name .DS_Store -print0 | xargs -0 git rm -f --ignore-unmatch
```

2. add .gitignore file to ignore .DS_Store files
```
touch .gitignore
```
Add this line to .gitignore file.
```
**/.DS_Store
```

3. make a commit and push

https://gist.github.com/lohenyumnam/2b127b9c3d1435dc12a33613c44e6308

**Comment by kenthiroi** [comment]
Sweet, I was wondering about a solution for this!
